FROM docker.elastic.co/beats/filebeat:8.11.3

USER root

# Remove old config (if any) and copy yours
RUN rm -f /usr/share/filebeat/filebeat.yml
COPY filebeat.yml /usr/share/filebeat/filebeat.yml

# Set owner and permissions correctly
RUN chown root:root /usr/share/filebeat/filebeat.yml && chmod 600 /usr/share/filebeat/filebeat.yml

USER filebeat
